name: firebase_phone_auth_handler
description: An easy-to-use firebase phone authentication package to easily send and verify OTP's with auto-fetch OTP support via SMS.
version: 0.0.6
homepage: https://github.com/rithik-dev/firebase_phone_auth_handler

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.1.4
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: